language: node_js
node_js:
- '5'
branches:
  only:
  - /^v[0-9]/
before_script:
- npm install
- node_modules/.bin/bower install
- node_modules/.bin/gulp
- export NODE_ENV=test
after_success:
- export PKG_VERSION="$(node -e 'console.log(require("package.json").version)')"
- mkdir -p dpl_assets/$PKG_VERSION
- mkdir -p dpl_assets/lib-assets
- cp -r public/assets/* dpl_assets/$PKG_VERSION 
- cp -r public/lib-assets/* dpl_assets/lib-assets 
deploy:
- provider: s3
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: 
    secure: "ab91UByJQUb+InbiIeB9uik4zpwaV8Grxqj5TSKVi967hXH1FXZOxNU9xwbREZt/hgWOwhTCiCD5Exf5Jf0Y5s0hY/M8ULsrMqsrFCML+wY9tE3gOERfGFZUyM8qkhu/dCrzGTb8nob7fWTHcWYxVmVytFg+Fw9DowaX4fDPebE="
  bucket: app-static.octoblu.com
  region: us-west-2
  skip_cleanup: true
  local-dir: dpl_assets 
