language: node_js
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
  - public/lib
node_js:
- '0.10'
after_success:
- find public -name *.html | xargs sed -ir -e "s%=\"/assets%=\"//d2zw6j512x6z0x.cloudfront.net/$TRAVIS_BRANCH/$TRAVIS_COMMIT/assets%"
- mkdir -p build/$TRAVIS_BRANCH && tar --exclude public/lib --exclude public/assets -cf build/$TRAVIS_BRANCH/$TRAVIS_COMMIT-public.tar Dockerfile default.conf public
- tar --append -f build/$TRAVIS_BRANCH/$TRAVIS_COMMIT-public.tar public/lib/zeroclipboard/dist/ZeroClipboard.swf
- gzip build/$TRAVIS_BRANCH/$TRAVIS_COMMIT-public.tar
- mkdir -p dpl_static && cp build/$TRAVIS_BRANCH/$TRAVIS_COMMIT-public.tar.gz dpl_static/public.tar.gz
- mkdir -p dpl_cdn/$TRAVIS_BRANCH/$TRAVIS_COMMIT && cp -rf public/assets dpl_cdn/$TRAVIS_BRANCH/$TRAVIS_COMMIT
- for file in `find dpl_cdn -type f`; do gzip --best $file && mv $file.gz $file; done
before_script:
- if [ ${TRAVIS_BRANCH} == master ]; then export NODE_ENV=production; else export
  NODE_ENV=staging; fi
- cp .npmrc ~/.npmrc
- npm install
- node_modules/.bin/bower install
- node_modules/.bin/gulp
- export NODE_ENV=test
deploy:
- provider: s3
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: &1
      secure: "ab91UByJQUb+InbiIeB9uik4zpwaV8Grxqj5TSKVi967hXH1FXZOxNU9xwbREZt/hgWOwhTCiCD5Exf5Jf0Y5s0hY/M8ULsrMqsrFCML+wY9tE3gOERfGFZUyM8qkhu/dCrzGTb8nob7fWTHcWYxVmVytFg+Fw9DowaX4fDPebE="
  bucket: app.octoblu.com
  region: us-west-2
  skip_cleanup: true
  detect_encoding: true
  cache_control: max-age=31536000
  local-dir: dpl_cdn
- provider: s3
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: *1
  bucket: deploy-octoblu-static
  region: us-west-2
  skip_cleanup: true
  local-dir: build
- provider: s3
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: *1
  bucket: deploy-octoblu-static
  region: us-west-2
  skip_cleanup: true
  local-dir: dpl_static
